---
Title: "Presentation: type_1 error"
author: ""
date: ""
---

```{r, include=F}
library(parallel)
load("stephanie_1004.RData")
load("stephanie_1005.RData") # simulation/rmd/
load("stephanie_1006.RData")
load("stephanie_1007.RData")
m_size <- matrix(NA, nrow = 4, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 4, ncol = 1)
m_time <- matrix(NA, nrow = 4, ncol = 3)
v_rownames <- c(
    "stephanie_1004", "stephanie_1005",
    "stephanie_1006", "stephanie_1007"
)
rownames(m_size) <- v_rownames
rownames(m_sigma2_mse) <- v_rownames
rownames(m_time) <- v_rownames
```

```{r, 1004, include=F}
m_size[1, ] <- stephanie_1004[[1]]
m_sigma2_mse[1, ] <- stephanie_1004[[2]]
m_time[1, ] <- rowMeans(matrix(unlist(stephanie_1004[[3]]), nrow = 3))
```

```{r, 1005, include=F}
m_size[2, ] <- stephanie_1005[[1]]
m_sigma2_mse[2, ] <- stephanie_1005[[2]]
m_time[2, ] <- rowMeans(matrix(unlist(stephanie_1005[[3]]), nrow = 3))
```

```{r, 1006, include=F}
m_size[3, ] <- stephanie_1006[[1]]
m_sigma2_mse[3, ] <- stephanie_1006[[2]]
m_time[3, ] <- rowMeans(matrix(unlist(stephanie_1006[[3]]), nrow = 3))
```

```{r, 1007, include=F}
m_size[4, ] <- stephanie_1007[[1]]
m_sigma2_mse[4, ] <- stephanie_1007[[2]]
m_time[4, ] <- rowMeans(matrix(unlist(stephanie_1007[[3]]), nrow = 3))
```

```{r, summary_100f}
print("summary for 100 fixed")
m_size
m_sigma2_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```

```{r, stephanie_1004r, include = F}
load("stephanie_1004r.RData") # simulation/rmd/
m_size[1, ] <- (stephanie_1004[[1]][[1]] + stephanie_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (stephanie_1004[[1]][[2]] + stephanie_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (stephanie_1004[[1]][[3]] + stephanie_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (stephanie_1004[[1]][[4]] + stephanie_1004[[2]][[4]]) / 2
m_time[1, ] <- (stephanie_1004[[1]][[5]] + stephanie_1004[[2]][[5]]) / 2
```

```{r, stephanie_1007r, include = F}
load("stephanie_1007r.RData") # simulation/rmd/
m_size[2, ] <- (stephanie_1007[[1]][[1]] + stephanie_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (stephanie_1007[[1]][[2]] + stephanie_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (stephanie_1007[[1]][[3]] + stephanie_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (stephanie_1007[[1]][[4]] + stephanie_1007[[2]][[4]]) / 2
m_time[2, ] <- (stephanie_1007[[1]][[5]] + stephanie_1007[[2]][[5]]) / 2
```
```{r, summary_100r}
print("summary for 100 random")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```
```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, stephanie_5004r.bs, eval = F, include = F}
load("simulation/rmd/stephanie_5004_1.RData") # simulation/rmd/
load("simulation/rmd/stephanie_5004_2.RData")
load("simulation/rmd/stephanie_5004_3r.RData")
load("simulation/rmd/stephanie_5004_4.RData")
load("simulation/rmd/stephanie_5004_5.RData")

load("simulation/rmd/stephanie_5004_3.RData")
stephanie_5004 <- c(stephanie_5004_1, stephanie_5004_2, stephanie_5004_3, stephanie_5004_4, stephanie_5004_5)
for (i in seq_along(stephanie_5004)) {
    m_size[1, ] <- m_size[1, ] + stephanie_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + stephanie_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + stephanie_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + stephanie_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + stephanie_5004[[i]][[5]]
}

stephanie_5004 <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ]
)
save(stephanie_5004, file = "stephanie_5004.RData")
```

```{r, stephanie_5007r.bs, eval = F, include = F}
load("simulation/rmd/stephanie_5007_1r.RData") # simulation/rmd/
load("simulation/rmd/stephanie_5007_2r.RData")
load("simulation/rmd/stephanie_5007_3r.RData")
load("simulation/rmd/stephanie_5007_4r.RData")
load("simulation/rmd/stephanie_5007_5r.RData")
stephanie_5007_3[[1]][[5]] <- rowMeans(matrix(unlist(stephanie_5007_3[[1]][[5]]), nrow = 3))
stephanie_5007_3[[2]][[5]] <- rowMeans(matrix(unlist(stephanie_5007_3[[2]][[5]]), nrow = 3))
stephanie_5007 <- c(stephanie_5007_1, stephanie_5007_2, stephanie_5007_3, stephanie_5007_4, stephanie_5007_5)
for (i in seq_along(stephanie_5007)) {
    m_size[1, ] <- m_size[1, ] + stephanie_5007[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + stephanie_5007[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + stephanie_5007[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + stephanie_5007[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + stephanie_5007[[i]][[5]]
}

stephanie_5007r <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ]
)
save(stephanie_5007r, file = "stephanie_5007r.RData")
```
```{r, stephanie_5004r, include = F}
load("stephanie_5004.RData")
m_size[1, ] <- stephanie_5004[[1]] / 10
m_sigma2_mse[1, ] <- stephanie_5004[[2]] / 10
m_c0_mse[1, ] <- stephanie_5004[[3]] / 10
m_calt_mse[1, ] <- stephanie_5004[[4]] / 10
m_time[1, ] <- stephanie_5004[[5]] / 10
```

```{r, stephanie_5007r, include = F}
load("stephanie_5007r.RData")
m_size[2, ] <- stephanie_5007r[[1]] / 10
m_sigma2_mse[2, ] <- stephanie_5007r[[2]] / 10
m_c0_mse[2, ] <- stephanie_5007r[[3]] / 10
m_calt_mse[2, ] <- stephanie_5007r[[4]] / 10
m_time[2, ] <- stephanie_5007r[[5]] / 10
```
```{r, summary_500r}
print("summary for 500 random")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```
```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
m_c0_mse <- matrix(NA, nrow = 2, ncol = 1)
m_calt_mse <- matrix(NA, nrow = 2, ncol = 1)
m_time <- matrix(NA, nrow = 2, ncol = 3)
```

```{r, steface_1004r, include=F}
load("steface_1004rr.RData") # simulation/rmd/
m_size[1, ] <- (steface_1004[[1]][[1]] + steface_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (steface_1004[[1]][[2]] + steface_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (steface_1004[[1]][[3]] + steface_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (steface_1004[[1]][[4]] + steface_1004[[2]][[4]]) / 2
m_time[1, ] <- (steface_1004[[1]][[5]] + steface_1004[[2]][[5]]) / 2
```

```{r, steface_1007r, include=F}
load("steface_1007.RData") # simulation/rmd/
m_size[2, ] <- (steface_1007[[1]][[1]] + steface_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (steface_1007[[1]][[2]] + steface_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (steface_1007[[1]][[3]] + steface_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (steface_1007[[1]][[4]] + steface_1007[[2]][[4]]) / 2
m_time[2, ] <- (steface_1007[[1]][[5]] + steface_1007[[2]][[5]]) / 2
```
```{r, summary steface_100}
print("summary for 100 random face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```



```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```

```{r, steface_5004.bs, eval = F, include = F}
load("simulation/rmd/steface_5004_1.RData") # simulation/rmd/
load("simulation/rmd/steface_5004_2.RData")
load("simulation/rmd/steface_5004_3.RData")
load("simulation/rmd/steface_5004_4.RData")
load("simulation/rmd/steface_5004_5.RData")
steface_5004 <- c(steface_5004_1, steface_5004_2, steface_5004_3, steface_5004_4, steface_5004_5)
for (i in seq_along(steface_5004)) {
    m_size[1, ] <- m_size[1, ] + steface_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + steface_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + steface_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + steface_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + steface_5004[[i]][[5]]
}
seed.bs <- sapply(steface_5004, seed <- function(l_list) {
    l_list[[6]]
})
steface_5004 <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(steface_5004, file = "steface_5004.RData")
```
```{r, steface_5007.bs, eval = F, include = F}
load("simulation/rmd/steface_5007_1.RData") # simulation/rmd/
load("simulation/rmd/steface_5007_2.RData")
load("simulation/rmd/steface_5007_3.RData")
load("simulation/rmd/steface_5007_4.RData")
load("simulation/rmd/steface_5007_5.RData")
steface_5007 <- c(steface_5007_1, steface_5007_2, steface_5007_3, steface_5007_4, steface_5007_5)
for (i in seq_along(steface_5007)) {
    m_size[2, ] <- m_size[2, ] + steface_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + steface_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + steface_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + steface_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + steface_5007[[i]][[5]]
}
seed.bs <- sapply(steface_5007, seed <- function(l_list) {
    l_list[[6]]
})
steface_5007 <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(steface_5007, file = "steface_5007.RData")
```
```{r, steface_5004, include = F}
load("steface_5004.RData")
m_size[1, ] <- steface_5004[[1]] / 10
m_sigma2_mse[1, ] <- steface_5004[[2]] / 10
m_c0_mse[1, ] <- steface_5004[[3]] / 10
m_calt_mse[1, ] <- steface_5004[[4]] / 10
m_time[1, ] <- steface_5004[[5]] / 10
```
```{r, steface_5007, include = F}
load("steface_5007.RData")
m_size[2, ] <- steface_5007[[1]] / 10
m_sigma2_mse[2, ] <- steface_5007[[2]] / 10
m_c0_mse[2, ] <- steface_5007[[3]] / 10
m_calt_mse[2, ] <- steface_5007[[4]] / 10
m_time[2, ] <- steface_5007[[5]] / 10
```
```{r, summary steface_500}
print("summary for 500 random face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
m_c0_mse <- matrix(NA, nrow = 2, ncol = 1)
m_calt_mse <- matrix(NA, nrow = 2, ncol = 1)
m_time <- matrix(NA, nrow = 2, ncol = 3)
```

```{r, zero_1004, include=F}
load("zero_1004.RData") # simulation/rmd/
m_size[1, ] <- (steface_1004[[1]][[1]] + steface_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (steface_1004[[1]][[2]] + steface_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (steface_1004[[1]][[3]] + steface_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (steface_1004[[1]][[4]] + steface_1004[[2]][[4]]) / 2
m_time[1, ] <- (steface_1004[[1]][[5]] + steface_1004[[2]][[5]]) / 2
```

```{r, zero_1007, include=F}
load("zero_1007.RData") # simulation/rmd/
m_size[2, ] <- (steface_1007[[1]][[1]] + steface_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (steface_1007[[1]][[2]] + steface_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (steface_1007[[1]][[3]] + steface_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (steface_1007[[1]][[4]] + steface_1007[[2]][[4]]) / 2
m_time[2, ] <- (steface_1007[[1]][[5]] + steface_1007[[2]][[5]]) / 2
```
```{r, summary zero_100}
print("summary for 100 zero face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
m_c0_mse <- matrix(NA, nrow = 2, ncol = 1)
m_calt_mse <- matrix(NA, nrow = 2, ncol = 1)
m_time <- matrix(NA, nrow = 2, ncol = 3)
```

```{r, steface_1004n, include=F}
load("steface_1004n.RData") # simulation/rmd/
m_size[1, ] <- (steface_1004[[1]][[1]] + steface_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (steface_1004[[1]][[2]] + steface_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (steface_1004[[1]][[3]] + steface_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (steface_1004[[1]][[4]] + steface_1004[[2]][[4]]) / 2
m_time[1, ] <- (steface_1004[[1]][[5]] + steface_1004[[2]][[5]]) / 2
```

```{r, steface_1007n, include=F}
load("steface_1007n.RData") # simulation/rmd/
m_size[2, ] <- (steface_1007[[1]][[1]] + steface_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (steface_1007[[1]][[2]] + steface_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (steface_1007[[1]][[3]] + steface_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (steface_1007[[1]][[4]] + steface_1007[[2]][[4]]) / 2
m_time[2, ] <- (steface_1007[[1]][[5]] + steface_1007[[2]][[5]]) / 2
```
```{r, summary steface_100 n}
print("summary for 100 new step face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```

```{r, steface_5004n.bs, eval = F, include = F}
load("simulation/rmd/steface_5004_1n.RData") # simulation/rmd/
load("simulation/rmd/steface_5004_2n.RData")
load("simulation/rmd/steface_5004_3n.RData")
load("simulation/rmd/steface_5004_4n.RData")
load("simulation/rmd/steface_5004_5n.RData")
steface_5004 <- c(steface_5004_1, steface_5004_2, steface_5004_3, steface_5004_4, steface_5004_5)
for (i in seq_along(steface_5004)) {
    m_size[1, ] <- m_size[1, ] + steface_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + steface_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + steface_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + steface_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + steface_5004[[i]][[5]]
}
seed.bs <- sapply(steface_5004, seed <- function(l_list) {
    l_list[[6]]
})
steface_5004n <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(steface_5004n, file = "steface_5004n.RData")
```
```{r, steface_5007n.bs, eval = F, include = F}
load("simulation/rmd/steface_5007_1n.RData") # simulation/rmd/
load("simulation/rmd/steface_5007_2n.RData")
load("simulation/rmd/steface_5007_3n.RData")
load("simulation/rmd/steface_5007_4n.RData")
load("simulation/rmd/steface_5007_5n.RData")
steface_5007 <- c(steface_5007_1, steface_5007_2, steface_5007_3, steface_5007_4, steface_5007_5)
for (i in seq_along(steface_5007)) {
    m_size[2, ] <- m_size[2, ] + steface_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + steface_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + steface_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + steface_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + steface_5007[[i]][[5]]
}
seed.bs <- sapply(steface_5007, seed <- function(l_list) {
    l_list[[6]]
})
steface_5007n <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(steface_5007n, file = "steface_5007n.RData")
```
```{r, steface_5004n, include = F}
load("steface_5004n.RData")
m_size[1, ] <- steface_5004n[[1]] / 10
m_sigma2_mse[1, ] <- steface_5004n[[2]] / 10
m_c0_mse[1, ] <- steface_5004n[[3]] / 10
m_calt_mse[1, ] <- steface_5004n[[4]] / 10
m_time[1, ] <- steface_5004n[[5]] / 10
```
```{r, steface_5007n, include = F}
load("steface_5007n.RData")
m_size[2, ] <- steface_5007n[[1]] / 10
m_sigma2_mse[2, ] <- steface_5007n[[2]] / 10
m_c0_mse[2, ] <- steface_5007n[[3]] / 10
m_calt_mse[2, ] <- steface_5007n[[4]] / 10
m_time[2, ] <- steface_5007n[[5]] / 10
```
```{r, summary steface_500n}
print("summary for 500 new face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
m_c0_mse <- matrix(NA, nrow = 2, ncol = 1)
m_calt_mse <- matrix(NA, nrow = 2, ncol = 1)
m_time <- matrix(NA, nrow = 2, ncol = 3)
```

```{r, steface_1004t, include=F}
load("steface_1004t.RData") # simulation/rmd/
m_size[1, ] <- (steface_1004[[1]][[1]] + steface_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (steface_1004[[1]][[2]] + steface_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (steface_1004[[1]][[3]] + steface_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (steface_1004[[1]][[4]] + steface_1004[[2]][[4]]) / 2
m_time[1, ] <- (steface_1004[[1]][[5]] + steface_1004[[2]][[5]]) / 2
```

```{r, steface_1007t, include=F}
load("steface_1007t.RData") # simulation/rmd/
m_size[2, ] <- (steface_1007[[1]][[1]] + steface_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (steface_1007[[1]][[2]] + steface_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (steface_1007[[1]][[3]] + steface_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (steface_1007[[1]][[4]] + steface_1007[[2]][[4]]) / 2
m_time[2, ] <- (steface_1007[[1]][[5]] + steface_1007[[2]][[5]]) / 2
```
```{r, summary steface_100 t}
print("summary for 100 t step face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```

```{r, steface_5004t.bs, eval = F, include = F}
load("simulation/rmd/steface_5004_1t.RData") # simulation/rmd/
load("simulation/rmd/steface_5004_2t.RData")
load("simulation/rmd/steface_5004_3t.RData")
load("simulation/rmd/steface_5004_4t.RData")
load("simulation/rmd/steface_5004_5t.RData")
steface_5004 <- c(steface_5004_1, steface_5004_2, steface_5004_3, steface_5004_4, steface_5004_5)
for (i in seq_along(steface_5004)) {
    m_size[1, ] <- m_size[1, ] + steface_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + steface_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + steface_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + steface_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + steface_5004[[i]][[5]]
}
seed.bs <- sapply(steface_5004, seed <- function(l_list) {
    l_list[[6]]
})
steface_5004t <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(steface_5004t, file = "steface_5004t.RData")
```
```{r, steface_5007t.bs, eval = F, include = F}
load("simulation/rmd/steface_5007_1t.RData") # simulation/rmd/
load("simulation/rmd/steface_5007_2t.RData")
load("simulation/rmd/steface_5007_3t.RData")
load("simulation/rmd/steface_5007_4t.RData")
load("simulation/rmd/steface_5007_5t.RData")
steface_5007 <- c(steface_5007_1, steface_5007_2, steface_5007_3, steface_5007_4, steface_5007_5)
for (i in seq_along(steface_5007)) {
    m_size[2, ] <- m_size[2, ] + steface_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + steface_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + steface_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + steface_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + steface_5007[[i]][[5]]
}
seed.bs <- sapply(steface_5007, seed <- function(l_list) {
    l_list[[6]]
})
steface_5007t <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(steface_5007t, file = "steface_5007t.RData")
```
```{r, steface_5004t, include = F}
load("steface_5004t.RData")
m_size[1, ] <- steface_5004t[[1]] / 10
m_sigma2_mse[1, ] <- steface_5004t[[2]] / 10
m_c0_mse[1, ] <- steface_5004t[[3]] / 10
m_calt_mse[1, ] <- steface_5004t[[4]] / 10
m_time[1, ] <- steface_5004t[[5]] / 10
```
```{r, steface_5007t, include = F}
load("steface_5007t.RData")
m_size[2, ] <- steface_5007t[[1]] / 10
m_sigma2_mse[2, ] <- steface_5007t[[2]] / 10
m_c0_mse[2, ] <- steface_5007t[[3]] / 10
m_calt_mse[2, ] <- steface_5007t[[4]] / 10
m_time[2, ] <- steface_5007t[[5]] / 10
```
```{r, summary steface_500t}
print("summary for 500 t face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
m_c0_mse <- matrix(NA, nrow = 2, ncol = 1)
m_calt_mse <- matrix(NA, nrow = 2, ncol = 1)
m_time <- matrix(NA, nrow = 2, ncol = 3)
```

```{r, steface_1004nt, include=F}
load("steface_1004nt.RData") # simulation/rmd/
m_size[1, ] <- (steface_1004[[1]][[1]] + steface_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (steface_1004[[1]][[2]] + steface_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (steface_1004[[1]][[3]] + steface_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (steface_1004[[1]][[4]] + steface_1004[[2]][[4]]) / 2
m_time[1, ] <- (steface_1004[[1]][[5]] + steface_1004[[2]][[5]]) / 2
```

```{r, steface_1007nt, include=F}
load("steface_1007nt.RData") # simulation/rmd/
m_size[2, ] <- (steface_1007[[1]][[1]] + steface_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (steface_1007[[1]][[2]] + steface_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (steface_1007[[1]][[3]] + steface_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (steface_1007[[1]][[4]] + steface_1007[[2]][[4]]) / 2
m_time[2, ] <- (steface_1007[[1]][[5]] + steface_1007[[2]][[5]]) / 2
```
```{r, summary steface_100 nt}
print("summary for 100 no trunct step face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```

```{r, steface_5004nt.bs, eval = F, include = F}
load("simulation/rmd/steface_5004_1nt.RData") # simulation/rmd/
load("simulation/rmd/steface_5004_2nt.RData")
load("simulation/rmd/steface_5004_3nt.RData")
load("simulation/rmd/steface_5004_4nt.RData")
load("simulation/rmd/steface_5004_5nt.RData")
steface_5004 <- c(steface_5004_1, steface_5004_2, steface_5004_3, steface_5004_4, steface_5004_5)
for (i in seq_along(steface_5004)) {
    m_size[1, ] <- m_size[1, ] + steface_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + steface_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + steface_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + steface_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + steface_5004[[i]][[5]]
}
seed.bs <- sapply(steface_5004, seed <- function(l_list) {
    l_list[[6]]
})
steface_5004nt <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(steface_5004nt, file = "steface_5004nt.RData")
```
```{r, steface_5007nt.bs, eval = F, include = F}
load("simulation/rmd/steface_5007_1nt.RData") # simulation/rmd/
load("simulation/rmd/steface_5007_2nt.RData")
load("simulation/rmd/steface_5007_3nt.RData")
load("simulation/rmd/steface_5007_4nt.RData")
load("simulation/rmd/steface_5007_5nt.RData")
steface_5007 <- c(steface_5007_1, steface_5007_2, steface_5007_3, steface_5007_4, steface_5007_5)
for (i in seq_along(steface_5007)) {
    m_size[2, ] <- m_size[2, ] + steface_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + steface_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + steface_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + steface_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + steface_5007[[i]][[5]]
}
seed.bs <- sapply(steface_5007, seed <- function(l_list) {
    l_list[[6]]
})
steface_5007nt <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(steface_5007nt, file = "steface_5007nt.RData")
```
```{r, steface_5004nt, include = F}
load("steface_5004nt.RData")
m_size[1, ] <- steface_5004nt[[1]] / 10
m_sigma2_mse[1, ] <- steface_5004nt[[2]] / 10
m_c0_mse[1, ] <- steface_5004nt[[3]] / 10
m_calt_mse[1, ] <- steface_5004nt[[4]] / 10
m_time[1, ] <- steface_5004nt[[5]] / 10
```
```{r, steface_5007nt, include = F}
load("steface_5007nt.RData")
m_size[2, ] <- steface_5007nt[[1]] / 10
m_sigma2_mse[2, ] <- steface_5007nt[[2]] / 10
m_c0_mse[2, ] <- steface_5007nt[[3]] / 10
m_calt_mse[2, ] <- steface_5007nt[[4]] / 10
m_time[2, ] <- steface_5007nt[[5]] / 10
```
```{r, summary steface_500nt}
print("summary for 500 no truncate face")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 4)
m_code <- matrix(NA, nrow = 2, ncol = 4)
m_plain <- matrix(NA, nrow = 2, ncol = 4)
```
```{r, quad_1004, include=F}
load("steface_quad_1004.RData") # simulation/rmd/
for (i in 1:4) {
    m_size[1, i] <- steface_quad_1004[[i]][[1]]
}
load("code_quad_1004.RData")
for (i in 1:4) {
    m_code[1, i] <- code_quad_1004[[i]][[1]]
}
load("plain_quad_1004.RData")
for (i in 1:4) {
    m_plain[1, i] <- code_quad_1004[[i]][[1]]
}
```
```{r, quad_1007, include=F}
load("steface_quad_1007.RData") # simulation/rmd/
for (i in 1:4) {
    m_size[2, i] <- steface_quad_1007[[i]][[1]]
}
load("code_quad_1007.RData")
for (i in 1:4) {
    m_code[2, i] <- code_quad_1007[[i]][[1]]
}
load("plain_quad_1007.RData")
for (i in 1:4) {
    m_plain[2, i] <- code_quad_1007[[i]][[1]]
}
```
```{r, summary quad_100}
print("summary for quad 100")
m_size
m_code
m_plain
```
```{r,  plot quad_100}
pdf(file = "quad_100.pdf")

par(mfrow = c(1, 1))
v_dev <- seq(0, 1, length.out = 5)
plot(v_dev, c(0.0524, m_size[1, ]),
    ylim = c(0, 1),
    type = "l", lty = 2, col = 1, lwd = 2,
    main = "Power under Quadratic Deviations", xlab = "Deviatin from Null", ylab = "Power, Quadratic Dev."
)
lines(v_dev, c(0.0444, m_size[2, ]), ylim = c(0, 1), lty = 1, col = 1, lwd = 2)
lines(v_dev, c(0.0510, m_code[1, ]), ylim = c(0, 1), lty = 2, col = "red", lwd = 2)
lines(v_dev, c(0.0472, m_code[2, ]), ylim = c(0, 1), lty = 1, col = "red", lwd = 2)
lines(v_dev, c(0.1074, m_plain[1, ]), ylim = c(0, 1), lty = 2, col = "blue", lwd = 2)
lines(v_dev, c(0.0752, m_plain[2, ]), ylim = c(0, 1), lty = 1, col = "blue", lwd = 2)
legend("bottomright",
    legend = c("Sparse test(t=80), m = 7", "Sparse test(optimal), m = 7", "Original test, m = 7", "Sparse test(t=80), m = 4", "Sparse test(optimal), m = 4", "Original test, m = 4"),
    col = rep(c("red", "black", "blue"), 2), lty = rep(1:2, each = 3), lwd = rep(2, 6)
)

abline(h = 1, lty = "dotted", col = "red")
abline(h = 0.05, lty = "dotted", col = "red")
dev.off()
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 4)
m_code <- matrix(NA, nrow = 2, ncol = 4)
m_plain <- matrix(NA, nrow = 2, ncol = 4)
```
```{r, trig_1004, include=F}
load("steface_trig_1004.RData") # simulation/rmd/
for (i in 1:4) {
    m_size[1, i] <- steface_trig_1004[[i]][[1]]
}
load("code_trig_1004.RData")
for (i in 1:4) {
    m_code[1, i] <- code_trig_1004[[i]][[1]]
}
load("plain_trig_1004.RData")
for (i in 1:4) {
    m_plain[1, i] <- code_trig_1004[[i]][[1]]
}
```
```{r, trig_1007, include=F}
load("steface_trig_1007.RData") # simulation/rmd/
for (i in 1:4) {
    m_size[2, i] <- steface_trig_1007[[i]][[1]]
}
load("code_trig_1007.RData")
for (i in 1:4) {
    m_code[2, i] <- code_trig_1007[[i]][[1]]
}
load("plain_trig_1007.RData")
for (i in 1:4) {
    m_plain[2, i] <- code_trig_1007[[i]][[1]]
}
```
```{r, summary trig_100}
print("summary for steface_trig")
m_size
m_code
m_plain
```
```{r,  plot trig_100}
pdf(file = "trig_100.pdf")

par(mfrow = c(1, 1))
v_dev <- seq(0, 1, length.out = 5)
plot(v_dev, c(0.0524, m_size[1, ]),
    ylim = c(0, 1),
    type = "l", lty = 2, col = 1, lwd = 2,
    main = "Power under Trigonometric Deviations", xlab = "Deviatin from Null", ylab = "Power, Trigonometric Dev."
)
lines(v_dev, c(0.0444, m_size[2, ]), ylim = c(0, 1), lty = 1, col = 1, lwd = 2)
lines(v_dev, c(0.0510, m_code[1, ]), ylim = c(0, 1), lty = 2, col = "red", lwd = 2)
lines(v_dev, c(0.0472, m_code[2, ]), ylim = c(0, 1), lty = 1, col = "red", lwd = 2)
lines(v_dev, c(0.1074, m_plain[1, ]), ylim = c(0, 1), lty = 2, col = "blue", lwd = 2)
lines(v_dev, c(0.0752, m_plain[2, ]), ylim = c(0, 1), lty = 1, col = "blue", lwd = 2)
legend("bottomright",
    legend = c("Sparse test(t=80), m = 7", "Sparse test(optimal), m = 7", "Original test, m = 7", "Sparse test(t=80), m = 4", "Sparse test(optimal), m = 4", "Original test, m = 4"),
    col = rep(c("red", "black", "blue"), 2), lty = rep(1:2, each = 3), lwd = rep(2, 6)
)

abline(h = 1, lty = "dotted", col = "red")
abline(h = 0.05, lty = "dotted", col = "red")

dev.off()
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
m_time <- matrix(NA, nrow = 2, ncol = 3)
```
```{r, steface_1004_025, include=F}
load("steface_1004_025.RData") # simulation/rmd/
m_size[1, ] <- (steface_1004[[1]][[1]] + steface_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (steface_1004[[1]][[2]] + steface_1004[[2]][[2]]) / 2
m_time[1, ] <- (steface_1004[[1]][[5]] + steface_1004[[2]][[5]]) / 2
```
```{r, steface_1007_025, include=F}
load("steface_1007_025.RData") # simulation/rmd/
m_size[2, ] <- (steface_1007[[1]][[1]] + steface_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (steface_1007[[1]][[2]] + steface_1007[[2]][[2]]) / 2
m_time[2, ] <- (steface_1007[[1]][[5]] + steface_1007[[2]][[5]]) / 2
```
```{r, summary steface_100 025}
print("summary for 100 sigma = 0.25")
m_size
m_sigma2_mse
m_time
```


```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
```

```{r, steface_5004_025.bs, eval = F, include = F}
load("simulation/rmd/steface_5004_1_025.RData") # simulation/rmd/
load("simulation/rmd/steface_5004_2_025.RData")
load("simulation/rmd/steface_5004_3_025.RData")
load("simulation/rmd/steface_5004_4_025.RData")
load("simulation/rmd/steface_5004_5_025.RData")
steface_5004 <- c(steface_5004_1, steface_5004_2, steface_5004_3, steface_5004_4, steface_5004_5)
for (i in seq_along(steface_5004)) {
    m_size[1, ] <- m_size[1, ] + steface_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + steface_5004[[i]][[2]]
}
seed.bs <- sapply(steface_5004, seed <- function(l_list) {
    l_list[[3]]
})
steface_5004_025 <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    seed.bs
)
save(steface_5004_025, file = "steface_5004_025.RData")
```
```{r, steface_5007_025.bs, eval = F, include = F}
load("simulation/rmd/steface_5007_1_025.RData") # simulation/rmd/
load("simulation/rmd/steface_5007_2_025.RData")
load("simulation/rmd/steface_5007_3_025.RData")
load("simulation/rmd/steface_5007_4_025.RData")
load("simulation/rmd/steface_5007_5_025.RData")
steface_5007 <- c(steface_5007_1, steface_5007_2, steface_5007_3, steface_5007_4, steface_5007_5)
for (i in seq_along(steface_5007)) {
    m_size[2, ] <- m_size[2, ] + steface_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + steface_5007[[i]][[2]]
}
seed.bs <- sapply(steface_5007, seed <- function(l_list) {
    l_list[[3]]
})
steface_5007_025 <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    seed.bs
)
save(steface_5007_025, file = "steface_5007_025.RData")
```
```{r, steface_5004_025, include = F}
load("steface_5004_025.RData") # simulation/rmd/
m_size[1, ] <- steface_5004_025[[1]] / 10
m_sigma2_mse[1, ] <- steface_5004_025[[2]] / 10
```
```{r, steface_5007_025, include = F}
load("steface_5007_025.RData")
m_size[2, ] <- steface_5007_025[[1]] / 10
m_sigma2_mse[2, ] <- steface_5007_025[[2]] / 10
```
```{r, summary steface_500_025}
print("summary for 500 025")
m_size
m_sigma2_mse
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
m_time <- matrix(NA, nrow = 2, ncol = 3)
```
```{r, steface_1004_04, include=F}
load("steface_1004_4.RData") # simulation/rmd/
m_size[1, ] <- (steface_1004[[1]][[1]] + steface_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (steface_1004[[1]][[2]] + steface_1004[[2]][[2]]) / 2
m_time[1, ] <- (steface_1004[[1]][[5]] + steface_1004[[2]][[5]]) / 2
```
```{r, steface_1007_04, include=F}
load("steface_1007_4.RData") # simulation/rmd/
m_size[2, ] <- (steface_1007[[1]][[1]] + steface_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (steface_1007[[1]][[2]] + steface_1007[[2]][[2]]) / 2
m_time[2, ] <- (steface_1007[[1]][[5]] + steface_1007[[2]][[5]]) / 2
```
```{r, summary steface_100 04}
print("summary for 100 sigma = 4")
m_size
m_sigma2_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
```

```{r, steface_5004_04.bs, eval = F, include = F}
load("simulation/rmd/steface_5004_1_4.RData") # simulation/rmd/
load("simulation/rmd/steface_5004_2_4.RData")
load("simulation/rmd/steface_5004_3_4.RData")
load("simulation/rmd/steface_5004_4_4.RData")
load("simulation/rmd/steface_5004_5_4.RData")
steface_5004 <- c(steface_5004_1, steface_5004_2, steface_5004_3, steface_5004_4, steface_5004_5)
for (i in seq_along(steface_5004)) {
    m_size[1, ] <- m_size[1, ] + steface_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + steface_5004[[i]][[2]]
}
seed.bs <- sapply(steface_5004, seed <- function(l_list) {
    l_list[[3]]
})
steface_5004_04 <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    seed.bs
)
save(steface_5004_04, file = "steface_5004_04.RData")
```
```{r, steface_5007_04.bs, eval = F, include = F}
load("simulation/rmd/steface_5007_1_4.RData") # simulation/rmd/
load("simulation/rmd/steface_5007_2_4.RData")
load("simulation/rmd/steface_5007_3_4.RData")
load("simulation/rmd/steface_5007_4_4.RData")
load("simulation/rmd/steface_5007_5_4.RData")
steface_5007 <- c(steface_5007_1, steface_5007_2, steface_5007_3, steface_5007_4, steface_5007_5)
for (i in seq_along(steface_5007)) {
    m_size[2, ] <- m_size[2, ] + steface_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + steface_5007[[i]][[2]]
}
seed.bs <- sapply(steface_5007, seed <- function(l_list) {
    l_list[[3]]
})
steface_5007_04 <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    seed.bs
)
save(steface_5007_04, file = "steface_5007_04.RData")
```
```{r, steface_5004_04, include = F}
load("steface_5004_04.RData") # simulation/rmd/
m_size[1, ] <- steface_5004_04[[1]] / 10
m_sigma2_mse[1, ] <- steface_5004_04[[2]] / 10
```
```{r, steface_5007_04, include = F}
load("steface_5007_04.RData")
m_size[2, ] <- steface_5007_04[[1]] / 10
m_sigma2_mse[2, ] <- steface_5007_04[[2]] / 10
```
```{r, summary steface_500_04}
print("summary for 500 sigma = 4")
m_size
m_sigma2_mse
```


```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
```
```{r, code_1004_025, include=F}
load("code_1004_025.RData") # simulation/rmd/
m_size[1, ] <- (code_1004[[1]][[1]] + code_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (code_1004[[1]][[2]] + code_1004[[2]][[2]]) / 2
```
```{r, code_1007_025, include=F}
load("code_1007_025.RData") # simulation/rmd/
m_size[2, ] <- (code_1007[[1]][[1]] + code_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (code_1007[[1]][[2]] + code_1007[[2]][[2]]) / 2
```
```{r, summary code_100 025}
print("summary for 100 approx sigma = 0.25")
m_size
m_sigma2_mse
```

```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
```
```{r, code_1004_4, include=F}
load("code_1004_4.RData") # simulation/rmd/
m_size[1, ] <- (code_1004[[1]][[1]] + code_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (code_1004[[1]][[2]] + code_1004[[2]][[2]]) / 2
```
```{r, code_1007_4, include=F}
load("code_1007_4.RData") # simulation/rmd/
m_size[2, ] <- (code_1007[[1]][[1]] + code_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (code_1007[[1]][[2]] + code_1007[[2]][[2]]) / 2
```
```{r, summary code_100 4}
print("summary for 100 approx sigma = 4")
m_size
m_sigma2_mse
```


```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
```
```{r, plain_1004_04, include=F}
load("plain_1004_4.RData") # simulation/rmd/
m_size[1, ] <- (code_1004[[1]][[1]] + code_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (code_1004[[1]][[2]] + code_1004[[2]][[2]]) / 2
```
```{r, plain_1007_04, include=F}
load("plain_1007_4.RData") # simulation/rmd/
m_size[2, ] <- (code_1007[[1]][[1]] + code_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (code_1007[[1]][[2]] + code_1007[[2]][[2]]) / 2
```
```{r, summary plain_100 04}
print("summary for plain 100 sigma = 4")
m_size
m_sigma2_mse
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
```
```{r, plain_5004_04.bs, eval = F, include = F}
load("simulation/rmd/plain_5004_1_4.RData") # simulation/rmd/
load("simulation/rmd/plain_5004_2_4.RData")
load("simulation/rmd/plain_5004_3_4.RData")
load("simulation/rmd/plain_5004_4_4.RData")
load("simulation/rmd/plain_5004_5_4.RData")
plain_5004 <- c(code_5004_1, code_5004_2, code_5004_3, code_5004_4, code_5004_5)
for (i in seq_along(plain_5004)) {
    m_size[1, ] <- m_size[1, ] + plain_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + plain_5004[[i]][[2]]
}
seed.bs <- sapply(plain_5004, seed <- function(l_list) {
    l_list[[3]]
})
plain_5004_04 <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    seed.bs
)
save(plain_5004_04, file = "plain_5004_04.RData")
```
```{r, plain_5007_04.bs, eval = F, include = F}
load("simulation/rmd/plain_5007_1_4.RData") # simulation/rmd/
load("simulation/rmd/plain_5007_2_4.RData")
load("simulation/rmd/plain_5007_3_4.RData")
load("simulation/rmd/plain_5007_4_4.RData")
load("simulation/rmd/plain_5007_5_4.RData")
plain_5007 <- c(code_5007_1, code_5007_2, code_5007_3, code_5007_4, code_5007_5)
for (i in seq_along(plain_5007)) {
    m_size[2, ] <- m_size[2, ] + plain_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + plain_5007[[i]][[2]]
}
seed.bs <- sapply(plain_5007, seed <- function(l_list) {
    l_list[[3]]
})
plain_5007_04 <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    seed.bs
)
save(plain_5007_04, file = "plain_5007_04.RData")
```
```{r, plain_5004_04, include = F}
load("plain_5004_04.RData") # simulation/rmd/
m_size[1, ] <- plain_5004_04[[1]] / 10
m_sigma2_mse[1, ] <- plain_5004_04[[2]] / 10
```
```{r, plain_5007_04, include = F}
load("plain_5007_04.RData")
m_size[2, ] <- plain_5007_04[[1]] / 10
m_sigma2_mse[2, ] <- plain_5007_04[[2]] / 10
```
```{r, summary plain_500_04}
print("summary for plain 500 sigma = 4")
m_size
m_sigma2_mse
```


```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 2, ncol = 1)
```
```{r, plain_1004_025, include=F}
load("plain_1004_025.RData") # simulation/rmd/
m_size[1, ] <- (code_1004[[1]][[1]] + code_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (code_1004[[1]][[2]] + code_1004[[2]][[2]]) / 2
```
```{r, plain_1007_025, include=F}
load("plain_1007_025.RData") # simulation/rmd/
m_size[2, ] <- (code_1007[[1]][[1]] + code_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (code_1007[[1]][[2]] + code_1007[[2]][[2]]) / 2
```
```{r, summary plain_100 025}
print("summary for plain 100 sigma = 0.25")
m_size
m_sigma2_mse
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
```
```{r, plain_5004_025.bs, eval = F, include = F}
load("simulation/rmd/plain_5004_1_025.RData") # simulation/rmd/
load("simulation/rmd/plain_5004_2_025.RData")
load("simulation/rmd/plain_5004_3_025.RData")
load("simulation/rmd/plain_5004_4_025.RData")
load("simulation/rmd/plain_5004_5_025.RData")
plain_5004 <- c(code_5004_1, code_5004_2, code_5004_3, code_5004_4, code_5004_5)
for (i in seq_along(plain_5004)) {
    m_size[1, ] <- m_size[1, ] + plain_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + plain_5004[[i]][[2]]
}
seed.bs <- sapply(plain_5004, seed <- function(l_list) {
    l_list[[3]]
})
plain_5004_025 <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    seed.bs
)
save(plain_5004_025, file = "plain_5004_025.RData")
```
```{r, plain_5007_025.bs, eval = F, include = F}
load("simulation/rmd/plain_5007_1_025.RData") # simulation/rmd/
load("simulation/rmd/plain_5007_2_025.RData")
load("simulation/rmd/plain_5007_3_025.RData")
load("simulation/rmd/plain_5007_4_025.RData")
load("simulation/rmd/plain_5007_5_025.RData")
plain_5007 <- c(code_5007_1, code_5007_2, code_5007_3, code_5007_4, code_5007_5)
for (i in seq_along(plain_5007)) {
    m_size[2, ] <- m_size[2, ] + plain_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + plain_5007[[i]][[2]]
}
seed.bs <- sapply(plain_5007, seed <- function(l_list) {
    l_list[[3]]
})
plain_5007_025 <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    seed.bs
)
save(plain_5007_025, file = "plain_5007_025.RData")
```
```{r, plain_5004_025, include = F}
load("plain_5004_025.RData") # simulation/rmd/
m_size[1, ] <- plain_5004_025[[1]] / 10
m_sigma2_mse[1, ] <- plain_5004_025[[2]] / 10
```
```{r, plain_5007_025, include = F}
load("plain_5007_025.RData")
m_size[2, ] <- plain_5007_025[[1]] / 10
m_sigma2_mse[2, ] <- plain_5007_025[[2]] / 10
```
```{r, summary plain_500_025}
print("summary for plain 500 sigma = 0.25")
m_size
m_sigma2_mse
```



```{r, include=F}
m_size <- matrix(NA, nrow = 2, ncol = 4)
m_code <- matrix(NA, nrow = 2, ncol = 4)
m_plain <- matrix(NA, nrow = 2, ncol = 4)
```
```{r, steface_5004_quad.bs, eval = F, include = F}
load("simulation/rmd/steface_quad_5004_2.RData")
load("simulation/rmd/steface_quad_5004_3.RData")
load("simulation/rmd/steface_quad_5004_4.RData")
load("simulation/rmd/steface_quad_5004_5.RData")
steface_5004_quad <- c(steface_5004_2, steface_5004_3, steface_5004_4, steface_5004_5)
for (i in 1:4) {
    temp <- 2 * i
    m_size[1, i] <- (steface_5004_quad[[temp-1]][[1]] + steface_5004_quad[[temp]][[1]])/2
}

steface_5004_quad <- list(
    m_size[1, ]
)
save(steface_5004_quad, file = "steface_5004_quad.RData")
```

```{r, steface_5007_quad.bs, eval = F, include = F}
load("simulation/rmd/steface_quad_5007_2.RData")
load("simulation/rmd/steface_quad_5007_3.RData")
load("simulation/rmd/steface_quad_5007_4.RData")
load("simulation/rmd/steface_quad_5007_5.RData")
steface_5007_quad <- c(steface_5007_2, steface_5007_3, steface_5007_4, steface_5007_5)
for (i in 1:4) {
    temp <- 2 * i
    m_size[2, i] <- (steface_5007_quad[[temp-1]][[1]] + steface_5007_quad[[temp]][[1]])/2
}

steface_5007_quad <- list(
    m_size[2, ]
)
save(steface_5007_quad, file = "steface_5007_quad.RData")
```

```{r, quad_5004, include=F}
load("steface_5004_quad.RData") # simulation/rmd/
for (i in 1:4) {
    m_size[1, i] <- steface_5004_quad[[1]][[i]]
}
# load("code_quad_5004.RData")
# for (i in 1:4) {
#     m_code[1, i] <- code_quad_1004[[i]][[1]]
# }
# load("plain_quad_5004.RData")
# for (i in 1:4) {
#     m_plain[1, i] <- code_quad_1004[[i]][[1]]
# }
```
```{r, quad_5007, include=F}
load("steface_5007_quad.RData") # simulation/rmd/
for (i in 1:4) {
    m_size[2, i] <- steface_5007_quad[[1]][[i]]
}
# load("code_quad_5007.RData")
# for (i in 1:4) {
#     m_code[2, i] <- code_quad_1007[[i]][[1]]
# }
# load("plain_quad_5007.RData")
# for (i in 1:4) {
#     m_plain[2, i] <- code_quad_1007[[i]][[1]]
# }
```
```{r, summary quad_500}
print("summary for quad 100")
m_size
# m_code
# m_plain
```
```{r,  plot quad_500}
#pdf(file = "quad_500.pdf")

par(mfrow = c(1, 1))
v_dev <- seq(0, 1, length.out = 5)
plot(v_dev, c(0.051, m_size[1, ]),
    ylim = c(0, 1),
    type = "l", lty = 2, col = 1, lwd = 2,
    main = "Power under Quadratic Deviations", xlab = "Deviatin from Null", ylab = "Power, Quadratic Dev."
)
lines(v_dev, c(0.041, m_size[2, ]), ylim = c(0, 1), lty = 1, col = 1, lwd = 2)
# lines(v_dev, c(0.0510, m_code[1, ]), ylim = c(0, 1), lty = 2, col = "red", lwd = 2)
# lines(v_dev, c(0.0472, m_code[2, ]), ylim = c(0, 1), lty = 1, col = "red", lwd = 2)
# lines(v_dev, c(0.1074, m_plain[1, ]), ylim = c(0, 1), lty = 2, col = "blue", lwd = 2)
# lines(v_dev, c(0.0752, m_plain[2, ]), ylim = c(0, 1), lty = 1, col = "blue", lwd = 2)
legend("bottomright",
    legend = c("Sparse test(t=80), m = 7", "Sparse test(optimal), m = 7", "Original test, m = 7", "Sparse test(t=80), m = 4", "Sparse test(optimal), m = 4", "Original test, m = 4"),
    col = rep(c("red", "black", "blue"), 2), lty = rep(1:2, each = 3), lwd = rep(2, 6)
)

abline(h = 1, lty = "dotted", col = "red")
abline(h = 0.05, lty = "dotted", col = "red")
#dev.off()
```
